[tool.poetry]
name = 'gcat'
version = '0.1.0-alpha'
description = 'A grid convergence analysis toolkit (GCAT) in Python.'
authors = ['Gabriel B. Santos <gabriel.bertacco@unesp.br>']
license = 'MIT'
readme = 'README.md'
repository = 'https://github.com/gabrielbdsantos/klingo'
keywords = ['mesh independence', 'grid convergence analysis', 'GCI']

[tool.poetry.dependencies]
python = '>=3.6'

[tool.poetry.dev-dependencies]
black = '*'
flake8 = '*'
isort = '*'
pydocstyle = '*'

[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'

[tool.black]
line-length = 79

[tool.pydocstyle]
convention = 'numpy'
